### ISSUE TITLE
skipTablePrefixes issue

### ISSUE THREAD

**Issue by jifenbao** [yuchenggroup/rapid-generator#1]
你好,我在使用这个工具的时候,发现了一个skipTablePrefixes的bug.
如果在generator.xml里面没有配置skipTablePrefixes的话,正常情况下应该所有的表都不忽略的.
但是在现在的代码里面,所有的表都忽略了.
看了下代码,是在GeneratorFacade.processByTable里面,如果没配置skipTablePrefixes,就给了他一个默认值"", 而sqlName.startsWith("")是永远为真的.所以就全部忽略了.
我大概修改了下
for(String prefix : prefixs.split(",")) {
                /*bug fix 
                如果在generator.xml里面没有配置skipTablePrefixes的话,所有的表都会被跳过.
                这个是不符合逻辑的  
                */
                if((null == prefix)|| ("".equalsIgnoreCase(prefix.trim())))
                {
                    continue;
                }

```
            if(sqlName.startsWith(prefix)) {
                GLogger.println("[skip]     matches prefix: " + prefix + "; skipTable: " + sqlName);
                return ;
            }
        }
```

感谢你维护这个框架~~

**Comment by renfufei** [comment]
已解决，感谢!
