### ISSUE TITLE
代码中需要保留 ${xxx} 格式的字符串，但是又和代码生成器的变量标示符 ${} 冲突，怎么处理？

### ISSUE THREAD

**Issue by wqlm** [yuchenggroup/rapid-generator#4]

**Comment by renfufei** [comment]
使用 `${r'XXXXXXX'}` 进行包裹:
例如:
```
${r'${'} XXXXXX ${r'}'}
```

参考 [countBy](https://github.com/yuchenggroup/rapid-generator/blob/master/template/cncounter-manage/src/main/resources/%24%7Bbasepackage_dir%7D/%24%7Bsubpackage_dir%7D/dao/mysql/%24%7BclassName%7DMapper.xml#L40)
